using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

// Generated by MyGeneration Version # (1.3.0.3)

namespace gp.ModeloDeDatos
{
    public class tx00201 : _TX00201
	{
        public tx00201(string sConnectionString)
		{
            this.ConnectionString = sConnectionString;
        }
	}
}
