//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegradorDeGP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM00200
    {
        public string VENDORID { get; set; }
        public string VENDNAME { get; set; }
        public string VNDCHKNM { get; set; }
        public string VENDSHNM { get; set; }
        public string VADDCDPR { get; set; }
        public string VADCDPAD { get; set; }
        public string VADCDSFR { get; set; }
        public string VADCDTRO { get; set; }
        public string VNDCLSID { get; set; }
        public string VNDCNTCT { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIPCODE { get; set; }
        public string COUNTRY { get; set; }
        public string PHNUMBR1 { get; set; }
        public string PHNUMBR2 { get; set; }
        public string PHONE3 { get; set; }
        public string FAXNUMBR { get; set; }
        public string UPSZONE { get; set; }
        public string SHIPMTHD { get; set; }
        public string TAXSCHID { get; set; }
        public string ACNMVNDR { get; set; }
        public string TXIDNMBR { get; set; }
        public short VENDSTTS { get; set; }
        public string CURNCYID { get; set; }
        public string TXRGNNUM { get; set; }
        public string PARVENID { get; set; }
        public short TRDDISCT { get; set; }
        public short TEN99TYPE { get; set; }
        public short TEN99BOXNUMBER { get; set; }
        public decimal MINORDER { get; set; }
        public string PYMTRMID { get; set; }
        public short MINPYTYP { get; set; }
        public short MINPYPCT { get; set; }
        public decimal MINPYDLR { get; set; }
        public short MXIAFVND { get; set; }
        public decimal MAXINDLR { get; set; }
        public string COMMENT1 { get; set; }
        public string COMMENT2 { get; set; }
        public string USERDEF1 { get; set; }
        public string USERDEF2 { get; set; }
        public decimal CRLMTDLR { get; set; }
        public string PYMNTPRI { get; set; }
        public byte KPCALHST { get; set; }
        public byte KGLDSTHS { get; set; }
        public byte KPERHIST { get; set; }
        public byte KPTRXHST { get; set; }
        public byte HOLD { get; set; }
        public short PTCSHACF { get; set; }
        public short CREDTLMT { get; set; }
        public short WRITEOFF { get; set; }
        public decimal MXWOFAMT { get; set; }
        public byte SBPPSDED { get; set; }
        public short PPSTAXRT { get; set; }
        public string DXVARNUM { get; set; }
        public System.DateTime CRTCOMDT { get; set; }
        public System.DateTime CRTEXPDT { get; set; }
        public byte RTOBUTKN { get; set; }
        public byte XPDTOBLG { get; set; }
        public byte PRSPAYEE { get; set; }
        public int PMAPINDX { get; set; }
        public int PMCSHIDX { get; set; }
        public int PMDAVIDX { get; set; }
        public int PMDTKIDX { get; set; }
        public int PMFINIDX { get; set; }
        public int PMMSCHIX { get; set; }
        public int PMFRTIDX { get; set; }
        public int PMTAXIDX { get; set; }
        public int PMWRTIDX { get; set; }
        public int PMPRCHIX { get; set; }
        public int PMRTNGIX { get; set; }
        public int PMTDSCIX { get; set; }
        public int ACPURIDX { get; set; }
        public int PURPVIDX { get; set; }
        public decimal NOTEINDX { get; set; }
        public string CHEKBKID { get; set; }
        public System.DateTime MODIFDT { get; set; }
        public System.DateTime CREATDDT { get; set; }
        public string RATETPID { get; set; }
        public byte Revalue_Vendor { get; set; }
        public short Post_Results_To { get; set; }
        public short FREEONBOARD { get; set; }
        public string GOVCRPID { get; set; }
        public string GOVINDID { get; set; }
        public short DISGRPER { get; set; }
        public short DUEGRPER { get; set; }
        public string DOCFMTID { get; set; }
        public byte TaxInvRecvd { get; set; }
        public short USERLANG { get; set; }
        public short WithholdingType { get; set; }
        public short WithholdingFormType { get; set; }
        public short WithholdingEntityType { get; set; }
        public short TaxFileNumMode { get; set; }
        public System.DateTime BRTHDATE { get; set; }
        public short LaborPmtType { get; set; }
        public string CCode { get; set; }
        public string DECLID { get; set; }
        public byte CBVAT { get; set; }
        public short Workflow_Approval_Status { get; set; }
        public short Workflow_Priority { get; set; }
        public string VADCD1099 { get; set; }
        public System.DateTime DEX_ROW_TS { get; set; }
        public int DEX_ROW_ID { get; set; }
    }
}
