//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegradorDeGP
{
    using System;
    using System.Collections.Generic;
    
    public partial class RM00101
    {
        public string CUSTNMBR { get; set; }
        public string CUSTNAME { get; set; }
        public string CUSTCLAS { get; set; }
        public string CPRCSTNM { get; set; }
        public string CNTCPRSN { get; set; }
        public string STMTNAME { get; set; }
        public string SHRTNAME { get; set; }
        public string ADRSCODE { get; set; }
        public string UPSZONE { get; set; }
        public string SHIPMTHD { get; set; }
        public string TAXSCHID { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string COUNTRY { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE2 { get; set; }
        public string PHONE3 { get; set; }
        public string FAX { get; set; }
        public string PRBTADCD { get; set; }
        public string PRSTADCD { get; set; }
        public string STADDRCD { get; set; }
        public string SLPRSNID { get; set; }
        public string CHEKBKID { get; set; }
        public string PYMTRMID { get; set; }
        public short CRLMTTYP { get; set; }
        public decimal CRLMTAMT { get; set; }
        public short CRLMTPER { get; set; }
        public decimal CRLMTPAM { get; set; }
        public string CURNCYID { get; set; }
        public string RATETPID { get; set; }
        public short CUSTDISC { get; set; }
        public string PRCLEVEL { get; set; }
        public short MINPYTYP { get; set; }
        public decimal MINPYDLR { get; set; }
        public short MINPYPCT { get; set; }
        public short FNCHATYP { get; set; }
        public short FNCHPCNT { get; set; }
        public decimal FINCHDLR { get; set; }
        public short MXWOFTYP { get; set; }
        public decimal MXWROFAM { get; set; }
        public string COMMENT1 { get; set; }
        public string COMMENT2 { get; set; }
        public string USERDEF1 { get; set; }
        public string USERDEF2 { get; set; }
        public string TAXEXMT1 { get; set; }
        public string TAXEXMT2 { get; set; }
        public string TXRGNNUM { get; set; }
        public short BALNCTYP { get; set; }
        public short STMTCYCL { get; set; }
        public string BANKNAME { get; set; }
        public string BNKBRNCH { get; set; }
        public string SALSTERR { get; set; }
        public short DEFCACTY { get; set; }
        public int RMCSHACC { get; set; }
        public int RMARACC { get; set; }
        public int RMSLSACC { get; set; }
        public int RMIVACC { get; set; }
        public int RMCOSACC { get; set; }
        public int RMTAKACC { get; set; }
        public int RMAVACC { get; set; }
        public int RMFCGACC { get; set; }
        public int RMWRACC { get; set; }
        public int RMSORACC { get; set; }
        public System.DateTime FRSTINDT { get; set; }
        public byte INACTIVE { get; set; }
        public byte HOLD { get; set; }
        public string CRCARDID { get; set; }
        public string CRCRDNUM { get; set; }
        public System.DateTime CCRDXPDT { get; set; }
        public byte KPDSTHST { get; set; }
        public byte KPCALHST { get; set; }
        public byte KPERHIST { get; set; }
        public byte KPTRXHST { get; set; }
        public decimal NOTEINDX { get; set; }
        public System.DateTime CREATDDT { get; set; }
        public System.DateTime MODIFDT { get; set; }
        public byte Revalue_Customer { get; set; }
        public short Post_Results_To { get; set; }
        public string FINCHID { get; set; }
        public string GOVCRPID { get; set; }
        public string GOVINDID { get; set; }
        public short DISGRPER { get; set; }
        public short DUEGRPER { get; set; }
        public string DOCFMTID { get; set; }
        public byte Send_Email_Statements { get; set; }
        public short USERLANG { get; set; }
        public string GPSFOINTEGRATIONID { get; set; }
        public short INTEGRATIONSOURCE { get; set; }
        public string INTEGRATIONID { get; set; }
        public short ORDERFULFILLDEFAULT { get; set; }
        public short CUSTPRIORITY { get; set; }
        public string CCode { get; set; }
        public string DECLID { get; set; }
        public int RMOvrpymtWrtoffAcctIdx { get; set; }
        public byte SHIPCOMPLETE { get; set; }
        public byte CBVAT { get; set; }
        public byte INCLUDEINDP { get; set; }
        public System.DateTime DEX_ROW_TS { get; set; }
        public int DEX_ROW_ID { get; set; }
    }
}
