//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegradorDeGP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwImpuestosPlanYDetalle
    {
        public string taxschid { get; set; }
        public string TAXDTLID { get; set; }
        public string TXDTLDSC { get; set; }
        public short TXDTLTYP { get; set; }
        public int ACTINDX { get; set; }
        public decimal TXDTLPCT { get; set; }
    }
}
